version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: lockmatch-mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: honghong
      MYSQL_DATABASE: mufyp
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-phonghong" ]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: lockmatch-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: honghong
      DB_NAME: mufyp
      JWT_SECRET: lockmatch2026_super_strong_key
      BASE_URL: http://localhost:3000
      PORT: 3000
    volumes:
      - .:/app
    working_dir: /app
